# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pushC2GRPC.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pushC2GRPC.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10pushC2GRPC.proto\x12\x0epushC2Services\"\xab\x01\n\x16PushC2MessageFromAgent\x12\x15\n\rC2ProfileName\x18\x01 \x01(\t\x12\x10\n\x08RemoteIP\x18\x02 \x01(\t\x12\x0f\n\x07Message\x18\x03 \x01(\x0c\x12\x11\n\tOuterUUID\x18\x04 \x01(\t\x12\x15\n\rBase64Message\x18\x05 \x01(\x0c\x12\x12\n\nTrackingID\x18\x06 \x01(\t\x12\x19\n\x11\x41gentDisconnected\x18\x07 \x01(\x08\"^\n\x17PushC2MessageFromMythic\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\r\n\x05\x45rror\x18\x02 \x01(\t\x12\x0f\n\x07Message\x18\x03 \x01(\x0c\x12\x12\n\nTrackingID\x18\x04 \x01(\t2\xef\x01\n\x06PushC2\x12m\n\x14StartPushC2Streaming\x12&.pushC2Services.PushC2MessageFromAgent\x1a\'.pushC2Services.PushC2MessageFromMythic\"\x00(\x01\x30\x01\x12v\n\x1dStartPushC2StreamingOneToMany\x12&.pushC2Services.PushC2MessageFromAgent\x1a\'.pushC2Services.PushC2MessageFromMythic\"\x00(\x01\x30\x01\x42/Z-github.com/its-a-feature/Mythic/grpc/servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pushC2GRPC_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/its-a-feature/Mythic/grpc/services'
  _globals['_PUSHC2MESSAGEFROMAGENT']._serialized_start=37
  _globals['_PUSHC2MESSAGEFROMAGENT']._serialized_end=208
  _globals['_PUSHC2MESSAGEFROMMYTHIC']._serialized_start=210
  _globals['_PUSHC2MESSAGEFROMMYTHIC']._serialized_end=304
  _globals['_PUSHC2']._serialized_start=307
  _globals['_PUSHC2']._serialized_end=546
# @@protoc_insertion_point(module_scope)
